# Dockerfile-server
# Use a Node.js image as the base
FROM node:14

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json to install dependencies
COPY server/package*.json ./server/

# Navigate to the server directory
WORKDIR /app/server

# Install dependencies
RUN npm install

# Copy the server source code
COPY . .

# Expose the port the server runs on
EXPOSE 8000

# Start the server
CMD ["node", "server.js"]
